import { Dice5Icon, CrownIcon, ClubIcon as FootballIcon, BirdIcon, FishIcon, HeartHandshakeIcon, TicketIcon } from 'lucide-react';
import { TypeIcon as type, LucideIcon } from 'lucide-react';

export interface Game {
  id: string
  name: string
  image: string
  category: string
}

export interface GameCategory {
  name: string;
  icon: LucideIcon;
}

export interface GameProvider {
  id: number;
  name: string;
  logo: string;
}

export const gameCategories: GameCategory[] = [
  { name: "Slot", icon: Dice5Icon },
  { name: "Casino", icon: CrownIcon },
  { name: "Fishing", icon: FishIcon },
  { name: "Poker", icon: HeartHandshakeIcon },
];

// Updated game image sources
export const allGames: Game[] = [
  { id: "game-1", name: "Ganga Club game-1", image: "/images/slot-game/FC-01.webp", category: "Slot" },
  { id: "game-2", name: "Ganga Club game-2", image: "/images/casino-game/EVOLIVE-01.webp", category: "Casino" },
  { id: "game-3", name: "Ganga Club game-3", image: "/images/fishing-game/FISHING-01.webp", category: "Fishing" },
  { id: "game-4", name: "Ganga Club game-4", image: "/images/poker-game/JL-Poker-01.webp", category: "Poker" },
  { id: "game-5", name: "Ganga Club game-5", image: "/images/poker-game/JL-Poker-02.webp", category: "Poker" },
  { id: "game-6", name: "Ganga Club game-6", image: "/images/slot-game/FC-02.webp", category: "Slot" },
  { id: "game-7", name: "Ganga Club game-7", image: "/images/slot-game/FC-03.webp", category: "Slot" },
  { id: "game-8", name: "Ganga Club game-8", image: "/images/casino-game/EVOLIVE-02.webp", category: "Casino" },
  { id: "game-9", name: "Ganga Club game-9", image: "/images/slot-game/FC-04.webp", category: "Slot" },
  { id: "game-10", name: "Ganga Club game-10", image: "/images/casino-game/EVOLIVE-03.webp", category: "Casino" },
  { id: "game-11", name: "Ganga Club game-11", image: "/images/fishing-game/FISHING-02.webp", category: "Fishing" },
  { id: "game-12", name: "Ganga Club game-12", image: "/images/poker-game/JL-Poker-03.webp", category: "Poker" },
  { id: "game-13", name: "Ganga Club game-13", image: "/images/slot-game/FC-05.webp", category: "Slot" },
  { id: "game-14", name: "Ganga Club game-14", image: "/images/slot-game/JDB-01.webp", category: "Slot" },
  { id: "game-15", name: "Ganga Club game-15", image: "/images/slot-game/JDB-02.webp", category: "Slot" },
  { id: "game-16", name: "Ganga Club game-16", image: "/images/slot-game/JDB-03.webp", category: "Slot" },
  { id: "game-17", name: "Ganga Club game-17", image: "/images/slot-game/JDB-04.webp", category: "Slot" },
  { id: "game-18", name: "Ganga Club game-18", image: "/images/slot-game/JDB-05.webp", category: "Slot" },
  { id: "game-19", name: "Ganga Club game-19", image: "/images/slot-game/JILI-01.webp", category: "Slot" },
  { id: "game-20", name: "Ganga Club game-20", image: "/images/slot-game/JILI-02.webp", category: "Slot" },
  { id: "game-21", name: "Ganga Club game-21", image: "/images/slot-game/JILI-03.webp", category: "Slot" },
  { id: "game-22", name: "Ganga Club game-22", image: "/images/slot-game/JILI-04.webp", category: "Slot" },
  { id: "game-23", name: "Ganga Club game-23", image: "/images/slot-game/JILI-05.webp", category: "Slot" },
  { id: "game-24", name: "Ganga Club game-24", image: "/images/slot-game/JILI-06.webp", category: "Slot" },
  { id: "game-25", name: "Ganga Club game-25", image: "/images/slot-game/PGS-01.webp", category: "Slot" },
  { id: "game-26", name: "Ganga Club game-26", image: "/images/slot-game/PGS-02.webp", category: "Slot" },
  { id: "game-27", name: "Ganga Club game-27", image: "/images/slot-game/PGS-03.webp", category: "Slot" },
  { id: "game-28", name: "Ganga Club game-28", image: "/images/slot-game/PGS-04.webp", category: "Slot" },
  { id: "game-29", name: "Ganga Club game-29", image: "/images/slot-game/PGS-05.webp", category: "Slot" },
  { id: "game-30", name: "Ganga Club game-30", image: "/images/slot-game/PGS-06.webp", category: "Slot" },
  { id: "game-31", name: "Ganga Club game-31", image: "/images/casino-game/EVOLIVE-04.webp", category: "Casino" },
  { id: "game-32", name: "Ganga Club game-32", image: "/images/casino-game/EVOLIVE-05.webp", category: "Casino" },
  { id: "game-33", name: "Ganga Club game-33", image: "/images/casino-game/EVOLIVE-06.webp", category: "Casino" },
  { id: "game-34", name: "Ganga Club game-34", image: "/images/casino-game/EVORNG-01.webp", category: "Casino" },
  { id: "game-35", name: "Ganga Club game-35", image: "/images/casino-game/EVORNG-02.webp", category: "Casino" },
  { id: "game-36", name: "Ganga Club game-36", image: "/images/casino-game/EVORNG-03.webp", category: "Casino" },
  { id: "game-37", name: "Ganga Club game-37", image: "/images/casino-game/EVORNG-04.webp", category: "Casino" },
  { id: "game-38", name: "Ganga Club game-38", image: "/images/casino-game/EVORNG-05.webp", category: "Casino" },
  { id: "game-39", name: "Ganga Club game-39", image: "/images/casino-game/EVORNG-06.webp", category: "Casino" },
  { id: "game-40", name: "Ganga Club game-40", image: "/images/casino-game/EZUGI-01.webp", category: "Casino" },
  { id: "game-41", name: "Ganga Club game-41", image: "/images/casino-game/EZUGI-02.webp", category: "Casino" },
  { id: "game-42", name: "Ganga Club game-42", image: "/images/casino-game/EZUGI-03.webp", category: "Casino" },
  { id: "game-43", name: "Ganga Club game-43", image: "/images/casino-game/EZUGI-04.webp", category: "Casino" },
  { id: "game-44", name: "Ganga Club game-44", image: "/images/casino-game/EZUGI-05.webp", category: "Casino" },
  { id: "game-45", name: "Ganga Club game-45", image: "/images/casino-game/EZUGI-06.webp", category: "Casino" },
  { id: "game-46", name: "Ganga Club game-46", image: "/images/fishing-game/FISHING-03.webp", category: "Fishing" },
  { id: "game-47", name: "Ganga Club game-47", image: "/images/fishing-game/FISHING-04.webp", category: "Fishing" },
  { id: "game-48", name: "Ganga Club game-48", image: "/images/fishing-game/FISHING-05.webp", category: "Fishing" },
  { id: "game-49", name: "Ganga Club game-49", image: "/images/fishing-game/FISHING-06.webp", category: "Fishing" },
  { id: "game-50", name: "Ganga Club game-50", image: "/images/fishing-game/FISHING-07.webp", category: "Fishing" },
  { id: "game-51", name: "Ganga Club game-51", image: "/images/fishing-game/FISHING-08.webp", category: "Fishing" },
  { id: "game-52", name: "Ganga Club game-52", image: "/images/fishing-game/FISHING-09.webp", category: "Fishing" },
  { id: "game-53", name: "Ganga Club game-53", image: "/images/fishing-game/FISHING-10.webp", category: "Fishing" },
  { id: "game-54", name: "Ganga Club game-54", image: "/images/fishing-game/FISHING-11.webp", category: "Fishing" },
  { id: "game-55", name: "Ganga Club game-55", image: "/images/fishing-game/FISHING-12.webp", category: "Fishing" },
  { id: "game-56", name: "Ganga Club game-56", image: "/images/fishing-game/FISHING-13.webp", category: "Fishing" },
  { id: "game-57", name: "Ganga Club game-57", image: "/images/fishing-game/FISHING-14.webp", category: "Fishing" },
  { id: "game-58", name: "Ganga Club game-58", image: "/images/fishing-game/FISHING-15.webp", category: "Fishing" },
  { id: "game-59", name: "Ganga Club game-59", image: "/images/fishing-game/FISHING-16.webp", category: "Fishing" },
  { id: "game-60", name: "Ganga Club game-60", image: "/images/fishing-game/FISHING-17.webp", category: "Fishing" },
  { id: "game-61", name: "Ganga Club game-61", image: "/images/poker-game/HB-Poker-01.webp", category: "Poker" },
  { id: "game-62", name: "Ganga Club game-62", image: "/images/poker-game/HB-Poker-02.webp", category: "Poker" },
  { id: "game-63", name: "Ganga Club game-63", image: "/images/poker-game/HB-Poker-03.webp", category: "Poker" },
  { id: "game-64", name: "Ganga Club game-64", image: "/images/poker-game/HB-Poker-04.webp", category: "Poker" },
  { id: "game-65", name: "Ganga Club game-65", image: "/images/poker-game/HB-Poker-05.webp", category: "Poker" },
  { id: "game-66", name: "Ganga Club game-66", image: "/images/poker-game/HB-Poker-06.webp", category: "Poker" },
  { id: "game-67", name: "Ganga Club game-67", image: "/images/poker-game/JL-Poker-04.webp", category: "Poker" },
  { id: "game-68", name: "Ganga Club game-68", image: "/images/poker-game/JL-Poker-05.webp", category: "Poker" },
  { id: "game-69", name: "Ganga Club game-69", image: "/images/poker-game/JL-Poker-06.webp", category: "Poker" },
  { id: "game-70", name: "Ganga Club game-70", image: "/images/poker-game/KM-Poker-01.webp", category: "Poker" },
  { id: "game-71", name: "Ganga Club game-71", image: "/images/poker-game/KM-Poker-02.webp", category: "Poker" },
  { id: "game-72", name: "Ganga Club game-72", image: "/images/poker-game/KM-Poker-03.webp", category: "Poker" },
  { id: "game-73", name: "Ganga Club game-73", image: "/images/poker-game/KM-Poker-04.webp", category: "Poker" },
  { id: "game-74", name: "Ganga Club game-74", image: "/images/poker-game/KM-Poker-05.webp", category: "Poker" },
  { id: "game-75", name: "Ganga Club game-75", image: "/images/poker-game/KM-Poker-06.webp", category: "Poker" },
];

export const gamesByCategory: { [key: string]: Game[] } = allGames.reduce(
  (acc, game) => {
    if (!acc[game.category]) {
      acc[game.category] = []
    }
    acc[game.category].push(game)
    return acc
  },
  {} as { [key: string]: Game[] },
);

export const gameProviders: GameProvider[] = [
  { id: 1, name: "Ganga Club game-provider-1", logo: "/images/providers-game/3s2.webp" },
  { id: 2, name: "Ganga Club game-provider-2", logo: "/images/providers-game/5g.webp" },
  { id: 3, name: "Ganga Club game-provider-3", logo: "/images/providers-game/7x.webp" },
  { id: 4, name: "Ganga Club game-provider-4", logo: "/images/providers-game/123bet.webp" },
  { id: 5, name: "Ganga Club game-provider-5", logo: "/images/providers-game/ab.webp" },
  { id: 6, name: "Ganga Club game-provider-6", logo: "/images/providers-game/ae.webp" },
  { id: 7, name: "Ganga Club game-provider-7", logo: "/images/providers-game/ail.webp" },
  { id: 8, name: "Ganga Club game-provider-8", logo: "/images/providers-game/ambs.webp" },
  { id: 9, name: "Ganga Club game-provider-9", logo: "/images/providers-game/amg.webp" },
  { id: 10, name: "Ganga Club game-provider-10", logo: "/images/providers-game/atg.webp" },
  { id: 11, name: "Ganga Club game-provider-11", logo: "/images/providers-game/auxx.webp" },
  { id: 12, name: "Ganga Club game-provider-12", logo: "/images/providers-game/aw.webp" },
  { id: 13, name: "Ganga Club game-provider-13", logo: "/images/providers-game/bga.webp" },
  { id: 14, name: "Ganga Club game-provider-14", logo: "/images/providers-game/bng.webp" },
  { id: 15, name: "Ganga Club game-provider-15", logo: "/images/providers-game/bom.webp" },
  { id: 16, name: "Ganga Club game-provider-16", logo: "/images/providers-game/bp.webp" },
  { id: 17, name: "Ganga Club game-provider-17", logo: "/images/providers-game/bsp.webp" },
  { id: 18, name: "Ganga Club game-provider-18", logo: "/images/providers-game/bt.webp" },
  { id: 19, name: "Ganga Club game-provider-19", logo: "/images/providers-game/btg.webp" },
  { id: 20, name: "Ganga Club game-provider-20", logo: "/images/providers-game/cfg.webp" },
  { id: 21, name: "Ganga Club game-provider-21", logo: "/images/providers-game/cg.webp" },
  { id: 22, name: "Ganga Club game-provider-22", logo: "/images/providers-game/cq9.webp" },
  { id: 23, name: "Ganga Club game-provider-23", logo: "/images/providers-game/crg.webp" },
  { id: 24, name: "Ganga Club game-provider-24", logo: "/images/providers-game/dg.webp" },
  { id: 25, name: "Ganga Club game-provider-25", logo: "/images/providers-game/drs.webp" },
  { id: 26, name: "Ganga Club game-provider-26", logo: "/images/providers-game/ds88.webp" },
  { id: 27, name: "Ganga Club game-provider-27", logo: "/images/providers-game/eg4.webp" },
  { id: 28, name: "Ganga Club game-provider-28", logo: "/images/providers-game/ep.webp" },
  { id: 29, name: "Ganga Club game-provider-29", logo: "/images/providers-game/es.webp" },
  { id: 30, name: "Ganga Club game-provider-30", logo: "/images/providers-game/ez.webp" },
  { id: 31, name: "Ganga Club game-provider-31", logo: "/images/providers-game/ezg.webp" },
  { id: 32, name: "Ganga Club game-provider-32", logo: "/images/providers-game/fc.webp" },
  { id: 33, name: "Ganga Club game-provider-33", logo: "/images/providers-game/fp.webp" },
  { id: 34, name: "Ganga Club game-provider-34", logo: "/images/providers-game/fs.webp" },
  { id: 35, name: "Ganga Club game-provider-35", logo: "/images/providers-game/ftg.webp" },
  { id: 36, name: "Ganga Club game-provider-36", logo: "/images/providers-game/gm.webp" },
  { id: 37, name: "Ganga Club game-provider-37", logo: "/images/providers-game/gpi.webp" },
  { id: 38, name: "Ganga Club game-provider-38", logo: "/images/providers-game/hc.webp" },
  { id: 39, name: "Ganga Club game-provider-39", logo: "/images/providers-game/hs.webp" },
  { id: 40, name: "Ganga Club game-provider-40", logo: "/images/providers-game/jdb.webp" },
  { id: 41, name: "Ganga Club game-provider-41", logo: "/images/providers-game/jili.webp" },
  { id: 42, name: "Ganga Club game-provider-42", logo: "/images/providers-game/ka.webp" },
  { id: 43, name: "Ganga Club game-provider-43", logo: "/images/providers-game/km.webp" },
  { id: 44, name: "Ganga Club game-provider-44", logo: "/images/providers-game/kp.webp" },
  { id: 45, name: "Ganga Club game-provider-45", logo: "/images/providers-game/ksg.webp" },
  { id: 46, name: "Ganga Club game-provider-46", logo: "/images/providers-game/l22.webp" },
  { id: 47, name: "Ganga Club game-provider-47", logo: "/images/providers-game/l365.webp" },
  { id: 48, name: "Ganga Club game-provider-48", logo: "/images/providers-game/ma.webp" },
];

// Data terpisah untuk baris marquee pertama (sekitar setengah dari gameProviders)
export const gameProvidersRow1: GameProvider[] = [
  { id: 1, name: "Ganga Club game-provider-1", logo: "/images/providers-game/3s2.webp" },
  { id: 2, name: "Ganga Club game-provider-2", logo: "/images/providers-game/5g.webp" },
  { id: 3, name: "Ganga Club game-provider-3", logo: "/images/providers-game/7x.webp" },
  { id: 4, name: "Ganga Club game-provider-4", logo: "/images/providers-game/123bet.webp" },
  { id: 5, name: "Ganga Club game-provider-5", logo: "/images/providers-game/ab.webp" },
  { id: 6, name: "Ganga Club game-provider-6", logo: "/images/providers-game/ae.webp" },
  { id: 7, name: "Ganga Club game-provider-7", logo: "/images/providers-game/ail.webp" },
  { id: 8, name: "Ganga Club game-provider-8", logo: "/images/providers-game/ambs.webp" },
  { id: 9, name: "Ganga Club game-provider-9", logo: "/images/providers-game/amg.webp" },
  { id: 10, name: "Ganga Club game-provider-10", logo: "/images/providers-game/atg.webp" },
  { id: 11, name: "Ganga Club game-provider-11", logo: "/images/providers-game/auxx.webp" },
  { id: 12, name: "Ganga Club game-provider-12", logo: "/images/providers-game/aw.webp" },
  { id: 13, name: "Ganga Club game-provider-13", logo: "/images/providers-game/bga.webp" },
  { id: 14, name: "Ganga Club game-provider-14", logo: "/images/providers-game/bng.webp" },
  { id: 15, name: "Ganga Club game-provider-15", logo: "/images/providers-game/bom.webp" },
  { id: 16, name: "Ganga Club game-provider-16", logo: "/images/providers-game/bp.webp" },
  { id: 17, name: "Ganga Club game-provider-17", logo: "/images/providers-game/bsp.webp" },
  { id: 18, name: "Ganga Club game-provider-18", logo: "/images/providers-game/bt.webp" },
  { id: 19, name: "Ganga Club game-provider-19", logo: "/images/providers-game/btg.webp" },
  { id: 20, name: "Ganga Club game-provider-20", logo: "/images/providers-game/cfg.webp" },
  { id: 21, name: "Ganga Club game-provider-21", logo: "/images/providers-game/cg.webp" },
  { id: 22, name: "Ganga Club game-provider-22", logo: "/images/providers-game/cq9.webp" },
  { id: 23, name: "Ganga Club game-provider-23", logo: "/images/providers-game/crg.webp" },
  { id: 24, name: "Ganga Club game-provider-24", logo: "/images/providers-game/dg.webp" },
  { id: 25, name: "Ganga Club game-provider-25", logo: "/images/providers-game/drs.webp" },
  { id: 26, name: "Ganga Club game-provider-26", logo: "/images/providers-game/ds88.webp" },
  { id: 27, name: "Ganga Club game-provider-27", logo: "/images/providers-game/eg4.webp" },
  { id: 28, name: "Ganga Club game-provider-28", logo: "/images/providers-game/ep.webp" },
  { id: 29, name: "Ganga Club game-provider-29", logo: "/images/providers-game/es.webp" },
  { id: 30, name: "Ganga Club game-provider-30", logo: "/images/providers-game/ez.webp" },
  { id: 31, name: "Ganga Club game-provider-31", logo: "/images/providers-game/ezg.webp" },
  { id: 32, name: "Ganga Club game-provider-32", logo: "/images/providers-game/fc.webp" },
  { id: 33, name: "Ganga Club game-provider-33", logo: "/images/providers-game/fp.webp" },
  { id: 34, name: "Ganga Club game-provider-34", logo: "/images/providers-game/fs.webp" },
  { id: 35, name: "Ganga Club game-provider-35", logo: "/images/providers-game/ftg.webp" },
  { id: 36, name: "Ganga Club game-provider-36", logo: "/images/providers-game/gm.webp" },
  { id: 37, name: "Ganga Club game-provider-37", logo: "/images/providers-game/gpi.webp" },
  { id: 38, name: "Ganga Club game-provider-38", logo: "/images/providers-game/hc.webp" },
  { id: 39, name: "Ganga Club game-provider-39", logo: "/images/providers-game/hs.webp" },
  { id: 40, name: "Ganga Club game-provider-40", logo: "/images/providers-game/jdb.webp" },
  { id: 41, name: "Ganga Club game-provider-41", logo: "/images/providers-game/jili.webp" },
  { id: 42, name: "Ganga Club game-provider-42", logo: "/images/providers-game/ka.webp" },
  { id: 43, name: "Ganga Club game-provider-43", logo: "/images/providers-game/km.webp" },
  { id: 44, name: "Ganga Club game-provider-44", logo: "/images/providers-game/kp.webp" },
  { id: 45, name: "Ganga Club game-provider-45", logo: "/images/providers-game/ksg.webp" },
  { id: 46, name: "Ganga Club game-provider-46", logo: "/images/providers-game/l22.webp" },
  { id: 47, name: "Ganga Club game-provider-47", logo: "/images/providers-game/l365.webp" },
  { id: 48, name: "Ganga Club game-provider-48", logo: "/images/providers-game/ma.webp" },
];

// Data terpisah untuk baris marquee kedua (sisa dari gameProviders)
export const gameProvidersRow2: GameProvider[] = [
  
  { id: 49, name: "Ganga Club game-provider-49", logo: "/images/providers-game/maha.webp" },
  { id: 50, name: "Ganga Club game-provider-50", logo: "/images/providers-game/mas.webp" },
  { id: 51, name: "Ganga Club game-provider-51", logo: "/images/providers-game/mg.webp" },
  { id: 52, name: "Ganga Club game-provider-52", logo: "/images/providers-game/mnc.webp" },
  { id: 53, name: "Ganga Club game-provider-53", logo: "/images/providers-game/mnp.webp" },
  { id: 54, name: "Ganga Club game-provider-54", logo: "/images/providers-game/mw.webp" },
  { id: 55, name: "Ganga Club game-provider-55", logo: "/images/providers-game/ne.webp" },
  { id: 56, name: "Ganga Club game-provider-56", logo: "/images/providers-game/ng.webp" },
  { id: 57, name: "Ganga Club game-provider-57", logo: "/images/providers-game/nlc.webp" },
  { id: 58, name: "Ganga Club game-provider-58", logo: "/images/providers-game/ns.webp" },
  { id: 59, name: "Ganga Club game-provider-59", logo: "/images/providers-game/octp.webp" },
  { id: 60, name: "Ganga Club game-provider-60", logo: "/images/providers-game/pas.webp" },
  { id: 61, name: "Ganga Club game-provider-61", logo: "/images/providers-game/pg.webp" },
  { id: 62, name: "Ganga Club game-provider-62", logo: "/images/providers-game/pin.webp" },
  { id: 63, name: "Ganga Club game-provider-63", logo: "/images/providers-game/pp.webp" },
  { id: 64, name: "Ganga Club game-provider-64", logo: "/images/providers-game/pre.webp" },
  { id: 65, name: "Ganga Club game-provider-65", logo: "/images/providers-game/ps.webp" },
  { id: 66, name: "Ganga Club game-provider-66", logo: "/images/providers-game/pt.webp" },
  { id: 67, name: "Ganga Club game-provider-67", logo: "/images/providers-game/r88.webp" },
  { id: 68, name: "Ganga Club game-provider-68", logo: "/images/providers-game/rcg.webp" },
  { id: 69, name: "Ganga Club game-provider-69", logo: "/images/providers-game/rg.webp" },
  { id: 70, name: "Ganga Club game-provider-70", logo: "/images/providers-game/rlx.webp" },
  { id: 71, name: "Ganga Club game-provider-71", logo: "/images/providers-game/rpg.webp" },
  { id: 72, name: "Ganga Club game-provider-72", logo: "/images/providers-game/rsg.webp" },
  { id: 73, name: "Ganga Club game-provider-73", logo: "/images/providers-game/rt.webp" },
  { id: 74, name: "Ganga Club game-provider-74", logo: "/images/providers-game/rtg.webp" },
  { id: 75, name: "Ganga Club game-provider-75", logo: "/images/providers-game/sa.webp" },
  { id: 76, name: "Ganga Club game-provider-76", logo: "/images/providers-game/sas.webp" },
  { id: 77, name: "Ganga Club game-provider-77", logo: "/images/providers-game/sex.webp" },
  { id: 78, name: "Ganga Club game-provider-78", logo: "/images/providers-game/sg.webp" },
  { id: 79, name: "Ganga Club game-provider-79", logo: "/images/providers-game/spb.webp" },
  { id: 80, name: "Ganga Club game-provider-80", logo: "/images/providers-game/ss.webp" },
  { id: 81, name: "Ganga Club game-provider-81", logo: "/images/providers-game/swg.webp" },
  { id: 82, name: "Ganga Club game-provider-82", logo: "/images/providers-game/tf.webp" },
  { id: 83, name: "Ganga Club game-provider-83", logo: "/images/providers-game/tp.webp" },
  { id: 84, name: "Ganga Club game-provider-84", logo: "/images/providers-game/txg.webp" },
  { id: 85, name: "Ganga Club game-provider-85", logo: "/images/providers-game/ug2.webp" },
  { id: 86, name: "Ganga Club game-provider-86", logo: "/images/providers-game/va.webp" },
  { id: 87, name: "Ganga Club game-provider-87", logo: "/images/providers-game/via.webp" },
  { id: 88, name: "Ganga Club game-provider-88", logo: "/images/providers-game/vivo.webp" },
  { id: 89, name: "Ganga Club game-provider-89", logo: "/images/providers-game/vt.webp" },
  { id: 90, name: "Ganga Club game-provider-90", logo: "/images/providers-game/wj.webp" },
  { id: 91, name: "Ganga Club game-provider-91", logo: "/images/providers-game/wm.webp" },
  { id: 92, name: "Ganga Club game-provider-92", logo: "/images/providers-game/wmm.webp" },
  { id: 93, name: "Ganga Club game-provider-93", logo: "/images/providers-game/wow.webp" },
  { id: 94, name: "Ganga Club game-provider-94", logo: "/images/providers-game/yb.webp" },
  { id: 95, name: "Ganga Club game-provider-95", logo: "/images/providers-game/ygd.webp" },
  { id: 96, name: "Ganga Club game-provider-96", logo: "/images/providers-game/yl.webp" },
];
